shizuka.version = "0.1.0"

[site]
title = "Shizuka"
description = "A Shizuka site"
url = "https://example.com"
base_path = "/"

[build]
output_dir     = "dist"
templates_glob = "templates/*.tmpl"
static_dir     = "static"
content_dir    = "content"

[build.transforms]
minify = true

[build.goldmark]
extensions = ["gfm", "table", "strikethrough", "tasklist", "deflist", "footnotes", "typographer"]
[build.goldmark.parser]
auto_heading_id = false
attribute       = false
[build.goldmark.renderer]
hardbreaks      = false
XHTML           = false
