[metadata]
name = "Shizuka Templates"
description = "Built-in starter templates for Shizuka"
version = "1.0.0"
shizuka_version = "0.1.0"

[templates]
items = ["minimal", "terrible"]
default = "minimal"
